pipeline {
    agent any

    stages {
        stage('Build and Deploy') {
            steps {
                
                sh 'sudo docker build -t chetana98/teams:1.0 .'    
            }
         }
    }
}