pipeline {
    agent any
      environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhubcreds')

    stages {
        stage('Build and Deploy') {
            steps {
                
                sh 'sudo docker build -t chetana98/teamsmembers:1.0 .'   
                sh 'sudo docker push chetana98/teamsmembers:1.0 .'
            }
         }
    }
}
