AWSTemplateFormatVersion: 2010-09-09
Description: creating two instances using cloudformation
Resources:
 BFASchemaRegistry: 
  Type: AWS::Glue::Registry
  Properties: 
   Description: "s3 bucket, IAM Roles, IAM Policies"


Resources:
  ChetanaJSEC2Instance1:
    Type: AWS::EC2::Instance
    Properties: 
      Availability zone: 
      ImageId: "ami-0d51edf70b350eb30"
      InstanceType: t2.micro
      KeyName: chetana.pem
      Tags :
        - Key: Name 
          Value : chetana-ec2-instance1

  ChetanaJSEC2Instance2:
    Type: AWS::EC2::Instance
    Properties: 
      Availability zone: 
      ImageId: "ami-0d51edf70b350eb30"
      InstanceType: t2.micro
      KeyName: chetana.pem
      Tags : 
        - Key: Name 
          Value : chetana-ec2-instance2
      



  ChetanaJSEBSVolume1:
    Type: AWS::EC2::Volume
  Properties: 
     AvailabilityZone: "us-east-1a"
     Size: 5
 

  ChetanaJSEBSVolume2:
    Type: AWS::EC2::Volume
  Properties: 
     AvailabilityZone: "us-east-1a"
     Size: 5



  ChetanaJSVolumeattachment1: 
     Type: AWS::EC2::VolumeAttachment
  Properties: 
    Device: /dev/sdh
    InstanceId: !Ref ChetanaJSEC2Instance1
    VolumeId: !Ref ChetanaJSEBSVolume1

  ChetanaJSVolumeattachment2: 
    Type: AWS::EC2::VolumeAttachment
        Properties: 
          Device: /dev/sdh
          InstanceId: !Ref ChetanaJSEC2Instance2
          VolumeId: !Ref ChetanaJSEBSVolume2
 



 Resources:
  ChetanaJSS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
        Properties:
          BucketName: "Chetana-s3bucket"




ChetanaJSIAMRole: 
  Type: AWS::IAM::Role
        Properties: 
          RoleName: "Chetana-role"
          AssumeRolePolicyDocument: Json
          Description: "role to attach s3 bucket"
  



ChetanaJSIAMPolicy: 
  Type: 'AWS::IAM::Policy'
        Properties:
          PolicyName: Chetana-S3bucket-policy-access
            PolicyDocument:
               Version: "2012-10-17"
               Statement:
               - Effect: Allow
                    Action: '*'       
                    Resource: '*'
                Groups:
                   - !Ref Chetana-s3bucketGroup



  Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: "IPV4"
      LoadBalancerAttributes: 
        - LoadBalancerAttribute
      Name: ChetanaJSNLB
      Scheme: internet-facing
      SecurityGroups: 
        - String
       Subnets: 
        - subnet-0b4aa4a28eb1cca39

  
   