AWSTemplateFormatVersion: 2010-09-09
Description: creating two instances using cloudformation

Resources:
  ChetanaJSEC2Instance1:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-east-1d
      ImageId: ami-09988af04120b3591
      InstanceType: t2.micro
      KeyName: chetanajs
      
  ChetanaJSEC2Instance2:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-east-1d
      ImageId: ami-09988af04120b3591
      InstanceType: t2.micro
      KeyName: chetanajs
      
  ChetanaEBSVolume1: 
    Type: AWS::EC2::Volume 
    Properties: 
      AvailabilityZone: "us-east-1d"
      Size: 5
  
  ChetanaEBSVolume2: 
    Type: AWS::EC2::Volume 
    Properties: 
      AvailabilityZone: "us-east-1d"
      Size: 5
  
  ChetanaJSVolumeattachment1: 
    Type: AWS::EC2::VolumeAttachment
    Properties: 
        Device: /dev/sdh
        InstanceId: !Ref ChetanaJSEC2Instance1
        VolumeId: !Ref ChetanaEBSVolume1

  ChetanaJSVolumeattachment2: 
    Type: AWS::EC2::VolumeAttachment
    Properties: 
        Device: /dev/sdh
        InstanceId: !Ref ChetanaJSEC2Instance2
        VolumeId: !Ref ChetanaEBSVolume2
  

  ChetanaJSS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "chetana-s3bucket"

  chetanaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: chetana-s3-access-policy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  
  chetanaIAMPolicy: 
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: Chetana-S3bucket-policy-access
      Roles:
        - !Ref chetanaIAMRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: 
              - !Sub arn:aws:s3:::${ChetanaJSS3Bucket}
              - !Sub arn:aws:s3:::${ChetanaJSS3Bucket}/*


  ChetanaNetworkLoadBalancer: 
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ChetanaNetworkLoadBalancer
      #IpAddressType: "ipv4"
      Scheme: internet-facing
      Type: network
      Subnets:
        - subnet-0f20cd810f0a56064

  ChetanaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: ChetanaTargetGroup
      Port: 80
      Protocol: TCP
      Targets:
        - Id: !Ref ChetanaJSEC2Instance1
          Port: 80
        - Id: !Ref ChetanaJSEC2Instance2
          Port: 80
      VpcId: vpc-07f878be34a5c3700  

  chetanaListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ChetanaNetworkLoadBalancer
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ChetanaTargetGroup

  
  
 


  